function pronadjiZastavu(nacija) {
    switch (nacija) {
        case "British":
            return "https://www.countryflags.io/gb/flat/48.png";
        case "Thai":
            return "https://www.countryflags.io/th/flat/48.png";
        case "German":
            return "https://www.countryflags.io/de/flat/48.png";
        case "Brazilian":
            return "https://www.countryflags.io/br/flat/48.png";
        case "French":
            return "https://www.countryflags.io/fr/flat/48.png";
        case "Finnish":
            return "https://www.countryflags.io/fi/flat/48.png";
        case "Italian":
            return "https://www.countryflags.io/it/flat/48.png";
        case "Australian":
            return "https://www.countryflags.io/au/flat/48.png";
        case "Austrian":
            return "https://www.countryflags.io/at/flat/48.png";
        case "Argentine":
            return "https://www.countryflags.io/ar/flat/48.png";
        case "American":
            return "https://www.countryflags.io/us/flat/48.png";
        case "Spanish":
            return "https://www.countryflags.io/es/flat/48.png";
        case "Canadian":
            return "https://www.countryflags.io/ca/flat/48.png";
        case "New Zealander":
            return "https://www.countryflags.io/nz/flat/48.png";
        case "Swedish":
            return "https://www.countryflags.io/se/flat/48.png";
        case "Belgian":
            return "https://www.countryflags.io/be/flat/48.png";
        case "South African":
            return "https://www.countryflags.io/za/flat/48.png";
        case "Colombian":
            return "https://www.countryflags.io/co/flat/48.png";
        case "Swiss":
            return "https://www.countryflags.io/ch/flat/48.png";
        case "Dutch":
            return "https://www.countryflags.io/nl/flat/48.png";
        case "Mexican":
            return "https://www.countryflags.io/mx/flat/48.png";
        case "Polish":
            return "https://www.countryflags.io/pl/flat/48.png";
        case "Venezuelan":
            return "https://www.countryflags.io/ve/flat/48.png";
        case "Monegasque":
            return "https://www.countryflags.io/mc/flat/48.png";
        case "Russian":
            return "https://www.countryflags.io/ru/flat/48.png";
        case "Danish":
            return "https://www.countryflags.io/dk/flat/48.png";
        case "Indian":
            return "https://www.countryflags.io/in/flat/48.png";
        case "Rhodesian":
            return "https://www.countryflags.io/zw/flat/48.png";
        case "Liechtensteiner":
            return "https://www.countryflags.io/li/flat/48.png";
        case "Japanese":
            return "https://www.countryflags.io/jp/flat/48.png";
        case "Irish":
            return "https://www.countryflags.io/ie/flat/48.png";
        case "Chilean":
            return "https://www.countryflags.io/cl/flat/48.png";
        case "Portuguese":
            return "https://www.countryflags.io/pt/flat/48.png";
        case "Czech":
            return "https://www.countryflags.io/cz/flat/48.png";
        case "Malaysian":
            return "https://www.countryflags.io/my/flat/48.png"; 
        case "Hungarian":
            return "https://www.countryflags.io/hu/flat/48.png";
        case "Indonesian":
            return "https://www.countryflags.io/id/flat/48.png";
    }
}